### ISSUE TITLE
S3: upload while reading input

### ISSUE THREAD

**Issue by AlexKordic** [livepeer/go-tools#2]
In `newfileUploadRequest()` func we have read of entire input into memory [`io.Copy(part, fData)`](https://github.com/livepeer/go-tools/blob/main/drivers/s3.go#L516) before starting HTTP request. 

The `fData` is `stdin` in [catalyst-uploader](https://github.com/livepeer/catalyst-uploader) project.

Mist output binaries should read input at same pace as output is written. Caching entire input before starting output hurts Mist server workflow.

**Comment by cyberj0g** [comment]
[io.Copy](https://github.com/golang/go/blob/dc8e2a6a8ec94f2c98ba20edd57932eba284efb1/src/io/io.go#L405) is implemented as blocking read loop of 32kb chunks, it doesn't read entire input. What's the root issue on Mist side?

**Comment by cyberj0g** [comment]
- AWS API doesn't support streaming upload directly
- One way to achieve something close is to use multipart upload, but minimum partition size is 5Mb, which makes it impractical for small files
